export const loginInfo = {
  cause: 'OK',
  userId: 'AAF1ABAQG00Zb2FH_KVjKQojDH0X',
  token: {
    base64:
      'Q2mFhly6nqWDKUCT4NEycVuFXpHfnS0ePeb0edtRjmJiIOd86v8-4Nmp4bdK3V6q87Gdr9g587rcQce38axEU5PjpLzuPzQUliNRQTAJDr2rZE2fl_c-ADMzThdK_aeJXVcfE0VmYuzVtk7CAnIDW_xqayVSH-TFdBExRZ9xDY0=',
    expires: '1675436873357078845',
  },
  policies: [],
  simpleUser: null,
  detailedUser: {
    id: 'AAF1ABAQG00Zb2FH_KVjKQojDH0X',
    username: 'mamta.chudasama@gramener.com',
    SfdcId: '',
    HubspotId: '',
    revision: {
      prev: '',
      curr: '1',
      createdAt: '2023-01-10T04:59:56.900097Z',
      createdBy: 'peter.d@gramenerit.com',
      updatedAt: '2023-02-03T11:07:41.871099Z',
      updatedBy: 'peter.d@gramenerit.com',
    },
    state: 'USER_STATE_ACTIVE',
    firstName: 'Mamta',
    locale: '',
    fullName: 'Mamta  Chudasama',
    timeZone: '',
    roleId: 'AAGFABA41Bc7IM9LuIJybfirJ1k9',
    type: 'AUTH_TYPE_LOCAL',
    email: 'mamta.chudasama@gramener.com',
    phone: '',
    notifyPref: '',
    LastLoginTime: '2023-02-03T11:07:13.779891Z',
    LastLogoutTime: '2023-02-03T11:07:41.871099Z',
    emailState: 'ID_STATE_VERIFIED',
    phoneState: 'ID_STATE_UNSPECIFIED',
    customUserInput: {},
    allowedEnterprises: [
      {
        id: 'AAFlABC9t6xwVlhL25B0GfMONsK8',
        name: 'Gramenerit',
        roleId: 'AAGFABA41Bc7IM9LuIJybfirJ1k9',
      },
    ],
    enterpriseId: 'AAFlABC9t6xwVlhL25B0GfMONsK8',
  },
  realm: null,
  enterprise: {
    id: 'AAFlABC9t6xwVlhL25B0GfMONsK8',
    name: 'Gramenerit',
    SfdcId: '',
    HubspotId: '',
    state: 'ENTERPRISE_STATE_ACTIVE',
    type: 'ENTERPRISE_TYPE_UNSPECIFIED',
    policyList: {
      list: [],
    },
    parentEntpId: 'AAFlABDe6Nm63ixF5LJBbk9Keqp6',
    azureSubId: '',
    title: 'Gramenerit',
    description: '',
    revision: {
      prev: '',
      curr: '1',
      createdAt: '2022-12-01T00:05:16.976055Z',
      createdBy: 'dan@zededa.com',
      updatedAt: '2022-12-01T00:05:16.976055Z',
      updatedBy: 'dan@zededa.com',
    },
    realms: [],
    attributes: {},
    inheritAuthFromParent: false,
    childEnterprises: [],
    controllerHostURL: '',
    streamEvents: null,
  },
  role: {
    id: 'AAGFABA41Bc7IM9LuIJybfirJ1k9',
    name: 'Coimbatore_Project',
    title: 'Coimbatore_Project',
    description: '',
    revision: {
      prev: '',
      curr: '1',
      createdAt: '2023-01-02T05:42:50.582341Z',
      createdBy: 'peter.d@gramenerit.com',
      updatedAt: '0001-01-01T00:00:00Z',
      updatedBy: 'peter.d@gramenerit.com',
    },
    type: 'USER_ROLE_USER_DEFINED',
    state: 'ROLE_STATE_ACTIVE',
    scopes: [
      {
        accessDevice: 'PermissionAccessCreateReadUpdateDelete',
        accessApp: '',
        accessUser: '',
        accessStorage: '',
        accessEnterprise: 'PermissionAccessRead',
        enterpriseFilter: ['srOwn'],
        projectFilter: ['6c053e4d-e7d4-463a-a5eb-50e17e663331'],
        accessEdgeApp: 'PermissionAccessCreateReadUpdateDelete',
        accessAppInstance: 'PermissionAccessCreateReadUpdateDelete',
      },
    ],
  },
  noOfLoginAttemptsLeft: 0,
  redirectUrl: '',
  loginToken: null,
  apiToken: null,
  passwordExpiryTime: '2023-07-09T04:59:57.612569Z',
  passwordExpiryNotificationPeriodInSeconds: 864000,
  tempToken: null,
}
